// Generated by CoffeeScript 1.6.3
(function() {
  var MongoClient, Server, crypto, dbHost, dbName, dbPort, mongoClient, _ref;

  crypto = require('crypto');

  _ref = require('mongodb'), MongoClient = _ref.MongoClient, Server = _ref.Server;

  dbPort = 27017;

  dbHost = 'localhost';

  dbName = 'node-login';

  mongoClient = new MongoClient(new Server('localhost', 27017));

  mongoClient.open(function(err, mongoClient) {
    var db1;
    db1 = mongoClient.db('myDb');
    if (err) {
      return console.log("error opening " + e);
    } else {
      return console.log("connected to database :: " + db1);
    }
  });

}).call(this);
