// Generated by CoffeeScript 1.6.3
(function() {
  var accountmanager;

  accountmanager = require('./account-manager');

  module.exports = function(app) {
    return app.get('/', function(req, res) {
      if ((req.cookies.username == null) || (req.cookies.password == null)) {
        console.log('login');
        return res.render('login', {
          title: 'Login'
        });
      } else {
        return console.log('else');
      }
    });
  };

}).call(this);
