// Generated by CoffeeScript 1.6.3
(function() {
  var accountmanager;

  accountmanager = require('./account-manager');

  module.exports = function(app) {
    app.get('/', function(req, res) {
      if ((req.cookies.username == null) || (req.cookies.password == null)) {
        return res.render('login', {
          title: 'Login'
        });
      }
    });
    return app.get('/signup', function(req, res) {
      return res.render('signup', {
        title: "Sign Up"
      });
    });
  };

}).call(this);
