// Generated by CoffeeScript 1.6.3
(function() {
  var mongoose, user, userSchema;

  mongoose = require('mongoose');

  userSchema = new mongoose.Schema({
    name: {
      first: {
        type: String,
        trim: true
      },
      last: {
        type: String,
        trim: true
      }
    },
    age: {
      type: String
    },
    email: {
      type: String
    },
    username: {
      type: String
    },
    password: {
      type: String
    }
  });

  user = mongoose.model('User', userSchema);

  module.exports.userSchema = userSchema;

  module.exports.user = user;

}).call(this);
