// Generated by CoffeeScript 1.6.3
(function() {
  var ObjectId, Schema, contractSchema, mongoose, safeDate, user, userSchema;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  ObjectId = Schema.ObjectId;

  safeDate = require('safe_datejs');

  userSchema = new Schema({
    name: {
      first: {
        type: String,
        trim: true
      },
      last: {
        type: String,
        trim: true
      }
    },
    age: {
      type: String
    },
    email: {
      type: String
    },
    username: {
      type: String,
      "default": ""
    },
    passhash: {
      type: String,
      "default": ""
    }
  });

  contractSchema = new Schema({
    creationDate: {
      type: Date,
      "default": Date.now()
    },
    principle: {
      type: Number
    },
    paymentDate: {
      type: Date
    },
    base58SendingAddress: {
      type: String,
      "default": ""
    },
    purchaser: {
      type: String,
      "default": ""
    }
  });

  user = mongoose.model('User', userSchema);

  module.exports.userSchema = userSchema;

  module.exports.user = user;

}).call(this);
