// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, loadSettings, port, router;

  express = require('express');

  loadSettings = require('./util').loadSettings;

  app = express();

  app.set('port', 80);

  app.set('views', __dirname + '/src/views/');

  app.set('view engine', 'jade');

  app.locals.pretty = true;

  app.use(express.bodyParser());

  app.use(express.cookieParser());

  app.use(express.session({
    secret: 'sheldon is the man'
  }));

  app.use(app.router);

  app.use(express["static"]("" + __dirname + "/public"));

  app.use(express.errorHandler({
    dumpExceptions: true,
    showStack: true
  }));

  router = require('./router');

  port = process.env.port || 3000;

  app.listen(port, function() {
    return console.log("Listening on " + port);
  });

}).call(this);
