// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, loadSettings, port;

  express = require('express');

  loadSettings = require('./util').loadSettings;

  app = express();

  app.set('view engine', 'jade');

  app.use(express.bodyParser());

  app.use(app.router);

  app.use(express["static"]("" + __dirname + "/../public"));

  app.use(express.errorHandler({
    dumpExceptions: true,
    showStack: true
  }));

  port = process.env.port || 3000;

  app.listen(port, function() {
    return console.log("Listening on " + port);
  });

}).call(this);
