// Generated by CoffeeScript 1.6.3
(function() {
  module["export"].REDIS_PORT = 6379;

  module["export"].REDIS_HOST = '127.0.0.1';

  module["export"].DB_HOST = '127.0.0.1';

  module["export"].dbUser = 'admin';

  module["export"].dbPass = 'alphaalphafoxtrot';

  module["export"].dbIP = '142.4.197.18';

  module["export"].dbPort = '27017';

  module["export"].dbString = "mongodb://" + this.dbUser + ":" + this.dbPass + "@" + this.dbIP + ":" + this.dbPort + "/";

}).call(this);
