// Generated by CoffeeScript 1.6.3
(function() {
  var loadSettings,
    __hasProp = {}.hasOwnProperty;

  loadSettings = function() {
    var e, k, localsettings, settings, v;
    settings = require('./settings');
    try {
      localsettings = require('./localsettings');
    } catch (_error) {
      e = _error;
      localsettings = {};
    }
    for (k in localsettings) {
      if (!__hasProp.call(localsettings, k)) continue;
      v = localsettings[k];
      settings[k] = v;
    }
    return settings;
  };

}).call(this);
